"""Typed persistence for every SotS model (P01; package since W0).

This package is the **only** place that runs SQL (plus `db.py` for
pragmas and migrations; enforced by `tests/unit/test_architecture.py`).
Split from `repo.py` in W0 with no behaviour change (AD-4); every
public name is re-exported here so `from sots.storage import repo`
keeps working unchanged.
"""

from __future__ import annotations

from sots.storage.repo._core import from_json, to_json
from sots.storage.repo.agents_grading import (
    get_agent_card,
    get_agent_run,
    get_budget_slice,
    get_grade_record,
    get_grader_health,
    list_agent_cards,
    list_agent_runs,
    list_budget_slices,
    list_grade_records,
    list_grader_health,
    save_agent_card,
    save_agent_run,
    save_budget_slice,
    save_grade_record,
    save_grader_health,
)
from sots.storage.repo.audience import (
    get_audience_brief,
    get_audience_scorecard,
    get_calibration_record,
    get_mechanics_finding,
    get_persona,
    get_persona_reaction,
    get_playbook_entry,
    list_audience_briefs,
    list_audience_scorecards,
    list_calibration_records,
    list_mechanics_findings,
    list_persona_reactions,
    list_personas,
    list_playbook_entries,
    save_audience_brief,
    save_audience_scorecard,
    save_calibration_record,
    save_mechanics_finding,
    save_persona,
    save_persona_reaction,
    save_playbook_entry,
)
from sots.storage.repo.documents import (
    get_chunk,
    get_document,
    get_unit,
    list_chunks,
    list_documents,
    list_units,
    save_chunk,
    save_document,
    save_unit,
)
from sots.storage.repo.evidence import (
    get_discovery_note,
    get_evidence,
    get_fetched_doc,
    get_search_hit,
    get_specialist_findings,
    get_supplement_doc,
    get_verdict,
    list_discovery_notes,
    list_evidence,
    list_fetched_docs,
    list_search_hits,
    list_specialist_findings,
    list_supplement_docs,
    list_verdicts,
    save_discovery_note,
    save_evidence,
    save_fetched_doc,
    save_search_hit,
    save_specialist_findings,
    save_supplement_doc,
    save_verdict,
)
from sots.storage.repo.expansion import (
    get_concept,
    get_concept_edge,
    get_concept_graph,
    get_critic_score,
    get_deep_research_report,
    get_expansion_thread,
    get_integration_brief,
    get_margin_note,
    get_research_brief,
    get_research_note,
    list_concept_edges,
    list_concept_graphs,
    list_concepts,
    list_critic_scores,
    list_deep_research_reports,
    list_expansion_threads,
    list_integration_briefs,
    list_margin_notes,
    list_research_briefs,
    list_research_notes,
    save_concept,
    save_concept_edge,
    save_concept_graph,
    save_critic_score,
    save_deep_research_report,
    save_expansion_thread,
    save_integration_brief,
    save_margin_note,
    save_research_brief,
    save_research_note,
)
from sots.storage.repo.idempotency import (
    idempotent_save,
    snapshot_counts,
)
from sots.storage.repo.infrastructure import (
    append_event,
    cache_delete,
    cache_get,
    cache_set,
    delete_checkpoint,
    delete_dead_letter,
    get_checkpoint,
    get_dead_letter,
    get_dialogue,
    get_summary,
    list_dead_letters,
    list_events,
    list_summaries,
    list_waivers,
    save_checkpoint,
    save_dead_letter,
    save_dialogue,
    save_summary,
    save_waiver,
)
from sots.storage.repo.legal_learning import (
    get_defense_memo,
    get_learning_change,
    get_legal_issue,
    get_position,
    get_prompt_trial,
    list_defense_memos,
    list_learning_changes,
    list_legal_issues,
    list_positions,
    list_prompt_trials,
    save_defense_memo,
    save_learning_change,
    save_legal_issue,
    save_position,
    save_prompt_trial,
)
from sots.storage.repo.media_psyche import (
    get_engine_finding,
    get_media_check,
    get_media_work,
    get_synthesis,
    list_engine_findings,
    list_media_checks,
    list_media_works,
    list_syntheses,
    save_engine_finding,
    save_media_check,
    save_media_work,
    save_synthesis,
)
from sots.storage.repo.narrative import (
    get_core_message,
    get_drift_report,
    get_message_mapping,
    get_shadow_report,
    get_voice_comparison,
    get_voice_fingerprint,
    list_core_messages,
    list_drift_reports,
    list_message_mappings,
    list_shadow_reports,
    list_voice_comparisons,
    list_voice_fingerprints,
    save_core_message,
    save_drift_report,
    save_message_mapping,
    save_shadow_report,
    save_voice_comparison,
    save_voice_fingerprint,
)
from sots.storage.repo.profile_runs import (
    count_cache_entries,
    get_author_profile,
    get_book_profile,
    get_cache_entry,
    get_chapter_brief,
    get_chapter_state,
    get_llm_call,
    get_run,
    list_author_profiles,
    list_book_profiles,
    list_chapter_briefs,
    list_chapter_states,
    list_llm_calls,
    list_runs,
    save_author_profile,
    save_book_profile,
    save_cache_entry,
    save_chapter_brief,
    save_chapter_state,
    save_llm_call,
    save_run,
)
from sots.storage.repo.proposals_rewrite import (
    get_cross_check_report,
    get_integration_plan_item,
    get_proposal,
    get_proposal_decision,
    get_revision,
    get_revision_hunk,
    get_style_guide,
    get_style_report,
    list_cross_check_reports,
    list_integration_plan_items,
    list_proposal_decisions,
    list_proposals,
    list_revision_hunks,
    list_revisions,
    list_style_guides,
    list_style_reports,
    save_cross_check_report,
    save_integration_plan_item,
    save_proposal,
    save_proposal_decision,
    save_revision,
    save_revision_hunk,
    save_style_guide,
    save_style_report,
)

__all__ = [
        "append_event", "cache_delete", "cache_get", "cache_set", "count_cache_entries",
        "delete_checkpoint", "delete_dead_letter", "from_json", "get_agent_card", "get_agent_run",
        "get_audience_brief", "get_audience_scorecard", "get_author_profile", "get_book_profile",
        "get_budget_slice", "get_cache_entry", "get_calibration_record", "get_chapter_brief",
        "get_chapter_state", "get_checkpoint", "get_chunk", "get_concept", "get_concept_edge",
        "get_concept_graph", "get_core_message", "get_critic_score", "get_cross_check_report",
        "get_dead_letter", "get_deep_research_report", "get_defense_memo", "get_dialogue",
        "get_discovery_note", "get_document", "get_drift_report", "get_engine_finding",
        "get_evidence", "get_expansion_thread", "get_fetched_doc", "get_grade_record",
        "get_grader_health", "get_integration_brief", "get_integration_plan_item",
        "get_learning_change", "get_legal_issue", "get_llm_call", "get_margin_note",
        "get_mechanics_finding", "get_media_check", "get_media_work", "get_message_mapping",
        "get_persona", "get_persona_reaction", "get_playbook_entry", "get_position",
        "get_prompt_trial", "get_proposal", "get_proposal_decision", "get_research_brief",
        "get_research_note", "get_revision", "get_revision_hunk", "get_run", "get_search_hit",
        "get_shadow_report", "get_specialist_findings", "get_style_guide", "get_style_report",
        "get_summary", "get_supplement_doc", "get_synthesis", "get_unit", "get_verdict",
        "get_voice_comparison", "get_voice_fingerprint", "idempotent_save", "list_agent_cards",
        "list_agent_runs", "list_audience_briefs", "list_audience_scorecards",
        "list_author_profiles", "list_book_profiles", "list_budget_slices",
        "list_calibration_records", "list_chapter_briefs", "list_chapter_states", "list_chunks",
        "list_concept_edges", "list_concept_graphs", "list_concepts", "list_core_messages",
        "list_critic_scores", "list_cross_check_reports", "list_dead_letters",
        "list_deep_research_reports", "list_defense_memos", "list_discovery_notes",
        "list_documents", "list_drift_reports", "list_engine_findings", "list_events",
        "list_evidence", "list_expansion_threads", "list_fetched_docs", "list_grade_records",
        "list_grader_health", "list_integration_briefs", "list_integration_plan_items",
        "list_learning_changes", "list_legal_issues", "list_llm_calls", "list_margin_notes",
        "list_mechanics_findings", "list_media_checks", "list_media_works", "list_message_mappings",
        "list_persona_reactions", "list_personas", "list_playbook_entries", "list_positions",
        "list_prompt_trials", "list_proposal_decisions", "list_proposals", "list_research_briefs",
        "list_research_notes", "list_revision_hunks", "list_revisions", "list_runs",
        "list_search_hits", "list_shadow_reports", "list_specialist_findings", "list_style_guides",
        "list_style_reports", "list_summaries", "list_supplement_docs", "list_syntheses",
        "list_units", "list_verdicts", "list_voice_comparisons", "list_voice_fingerprints",
        "list_waivers", "save_agent_card", "save_agent_run", "save_audience_brief",
        "save_audience_scorecard", "save_author_profile", "save_book_profile", "save_budget_slice",
        "save_cache_entry", "save_calibration_record", "save_chapter_brief", "save_chapter_state",
        "save_checkpoint", "save_chunk", "save_concept", "save_concept_edge", "save_concept_graph",
        "save_core_message", "save_critic_score", "save_cross_check_report", "save_dead_letter",
        "save_deep_research_report", "save_defense_memo", "save_dialogue", "save_discovery_note",
        "save_document", "save_drift_report", "save_engine_finding", "save_evidence",
        "save_expansion_thread", "save_fetched_doc", "save_grade_record", "save_grader_health",
        "save_integration_brief", "save_integration_plan_item", "save_learning_change",
        "save_legal_issue", "save_llm_call", "save_margin_note", "save_mechanics_finding",
        "save_media_check", "save_media_work", "save_message_mapping", "save_persona",
        "save_persona_reaction", "save_playbook_entry", "save_position", "save_prompt_trial",
        "save_proposal", "save_proposal_decision", "save_research_brief", "save_research_note",
        "save_revision", "save_revision_hunk", "save_run", "save_search_hit", "save_shadow_report",
        "save_specialist_findings", "save_style_guide", "save_style_report", "save_summary",
        "save_supplement_doc", "save_synthesis", "save_unit", "save_verdict",
        "save_voice_comparison", "save_voice_fingerprint", "save_waiver", "snapshot_counts",
        "to_json",
]
